# Generated by Django 5.2.1 on 2025-05-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_movie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
