# Generated by Django 5.2.1 on 2025-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_alter_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
